apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: discord-bot
        image: ghcr.io/stefanbs/tinaja-bot/tinaja-bot:06ebb91827ed3a1a43a288b62a20d566f72ca254
        ports:
        - containerPort: 8000
          name: metrics
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secret
              key: DISCORD_BOT_TOKEN
