apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-bot-token
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: SecretStore
    name: example-auth  # Must match SecretStore on the cluster
  target:
    name: discord-bot-secret # Name for the secret on the cluster
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: discord-bot-token
