name: build-and-push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          platforms: linux/amd64, linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Required because my username has uppercase chars
      - name: GitHub repository to lowercase
        run: |
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/tinaja-bot:latest
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/tinaja-bot:${{ github.sha }}
